### ISSUE TITLE
Nemoh tutorial fails to run

### ISSUE THREAD

**Issue by max-lg** [WEC-Sim/bemio#14]
Attempting to run:  /bemio/tutorials/nemoh/run.py 
produces this output:

Traceback (most recent call last):
  File "run.py", line 12, in <module>
    nemoh_data = NemohOutput(sim_dir='./data/two_body', cal_file='Nemoh.cal', results_dir='Results', mesh_dir='Mesh', out_name='./data/two_body.out')
  File "build/bdist.linux-x86_64/egg/bemio/io/nemoh.py", line 74, in __init__
  File "build/bdist.linux-x86_64/egg/bemio/io/nemoh.py", line 106, in _create_and_load_hydro_data_obj
  File "build/bdist.linux-x86_64/egg/bemio/data_structures/bem.py", line 479, in nondimensionalize_hydro_coeffs
TypeError: unsupported operand type(s) for /: 'str' and 'float'

I did a bit of debugging, line 479 of bem.py is: self.k = self.k/(self.rho*self.g)
At that point self.k == 'not_defined'

I think 'self.k' should have been initialized in bemio/io/nemoh.py with a call to read_kh()
I tried adding a call to that method before calling nondimensionalize_hydro_coeffs(). The next error I got is: 

  File "run.py", line 13, in <module>
    nemoh_data = NemohOutput(sim_dir='./data/two_body', cal_file='Nemoh.cal', results_dir='Results', mesh_dir='Mesh', out_name='./data/two_body.out')
  File "build/bdist.linux-x86_64/egg/bemio/io/nemoh.py", line 90, in __init__
  File "build/bdist.linux-x86_64/egg/bemio/io/nemoh.py", line 126, in _create_and_load_hydro_data_obj
  File "build/bdist.linux-x86_64/egg/bemio/data_structures/bem.py", line 484, in nondimensionalize_hydro_coeffs
AttributeError: 'HydrodynamicCoefficients' object has no attribute 'zero'

At this point I'm unsure if multiple variables aren't getting initialized, or if I'm on the wrong track.

On a side note, all the other tutorials run properly for me. Please let me know if there are any other details I can provide, or any other tests I can perform.
Thanks!

**Comment by lawsonro3** [comment]
Hi Max,

Sorry for the late response... this was indeed a problem when reading Nemoh files, but was fixed several versions ago in the bem.py "scale" function.

Update your code to the latest version of bemio and let me know if you are still having any problems. For reference, I just testing everything with a clean install of Anaconda Python and bemio and its working for me.
