### ISSUE TITLE
Bemio calling __init__.py

### ISSUE THREAD

**Issue by MattSharman** [WEC-Sim/bemio#18]
Hi all, 

Tried running the latest commit and am now getting this error:

---------------------------------------------------------------
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from bemio.io.nemoh import NemohOutput
  File "build\bdist.win-amd64\egg\bemio\__init__.py", line 1, in <module>
ImportError: No module named version

-------------------------------------------------------------------------
I can't even find where _ _init_ _.py is being called in nemoh.py :confounded:

**Comment by lawsonro3** [comment]
Hi Matt,

Not sure what your problem is, I'm not able to repeat your problem at all on Windows with Anaconda Python. I just did a clean clone and tested the repo - see below:

```
C:\Users\User\Documents\GitHub> git clone --depth 1 https://github.com/WEC-Sim/bemio.git bemio_test
Cloning into 'bemio_test'...
remote: Counting objects: 254, done.
remote: Compressing objects: 100% (207/207), done.
remote: Total 254 (delta 33), reused 209 (delta 29), pack-reused 0
Receiving objects: 100% (254/254), 54.80 MiB | 172.00 KiB/s, done.
Resolving deltas: 100% (33/33), done.
Checking connectivity... done.
Checking out files: 100% (244/244), done.
C:\Users\User\Documents\GitHub> cd .\bemio_test
C:\Users\User\Documents\GitHub\bemio_test [master]> dir


    Directory: C:\Users\User\Documents\GitHub\bemio_test


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         8/12/2015   6:08 AM            bemio
d----         8/12/2015   6:08 AM            doc
d----         8/12/2015   6:08 AM            tutorials
-a---         8/12/2015   6:08 AM        862 .gitignore
-a---         8/12/2015   6:08 AM        203 clean_install.py
-a---         8/12/2015   6:08 AM       1695 install_test.py
-a---         8/12/2015   6:08 AM        325 README.md
-a---         8/12/2015   6:08 AM         26 setup.cfg
-a---         8/12/2015   6:08 AM        965 setup.py
-a---         8/12/2015   6:08 AM        133 USERS_GUIDE.html


C:\Users\User\Documents\GitHub\bemio_test [master]> python .\setup.py install --user
running install
running bdist_egg
running egg_info
creating bemio.egg-info
writing requirements to bemio.egg-info\requires.txt
writing bemio.egg-info\PKG-INFO
writing top-level names to bemio.egg-info\top_level.txt
writing dependency_links to bemio.egg-info\dependency_links.txt
writing manifest file 'bemio.egg-info\SOURCES.txt'
reading manifest file 'bemio.egg-info\SOURCES.txt'
writing manifest file 'bemio.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\bemio
copying bemio\__init__.py -> build\lib\bemio
copying bemio\__version__.py -> build\lib\bemio
creating build\lib\bemio\data_structures
copying bemio\data_structures\bem.py -> build\lib\bemio\data_structures
copying bemio\data_structures\wave_excitation.py -> build\lib\bemio\data_structures
copying bemio\data_structures\__init__.py -> build\lib\bemio\data_structures
creating build\lib\bemio\io
copying bemio\io\aqwa.py -> build\lib\bemio\io
copying bemio\io\nemoh.py -> build\lib\bemio\io
copying bemio\io\output.py -> build\lib\bemio\io
copying bemio\io\wamit.py -> build\lib\bemio\io
copying bemio\io\__init__.py -> build\lib\bemio\io
creating build\lib\bemio\mesh_utilities
copying bemio\mesh_utilities\mesh.py -> build\lib\bemio\mesh_utilities
copying bemio\mesh_utilities\__init__.py -> build\lib\bemio\mesh_utilities
creating build\lib\bemio\runners
copying bemio\runners\nemoh.py -> build\lib\bemio\runners
copying bemio\runners\__init__.py -> build\lib\bemio\runners
creating build\lib\bemio\utilities
copying bemio\utilities\__init__.py -> build\lib\bemio\utilities
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\bemio
creating build\bdist.win-amd64\egg\bemio\data_structures
copying build\lib\bemio\data_structures\bem.py -> build\bdist.win-amd64\egg\bemio\data_structures
copying build\lib\bemio\data_structures\wave_excitation.py -> build\bdist.win-amd64\egg\bemio\data_structures
copying build\lib\bemio\data_structures\__init__.py -> build\bdist.win-amd64\egg\bemio\data_structures
creating build\bdist.win-amd64\egg\bemio\io
copying build\lib\bemio\io\aqwa.py -> build\bdist.win-amd64\egg\bemio\io
copying build\lib\bemio\io\nemoh.py -> build\bdist.win-amd64\egg\bemio\io
copying build\lib\bemio\io\output.py -> build\bdist.win-amd64\egg\bemio\io
copying build\lib\bemio\io\wamit.py -> build\bdist.win-amd64\egg\bemio\io
copying build\lib\bemio\io\__init__.py -> build\bdist.win-amd64\egg\bemio\io
creating build\bdist.win-amd64\egg\bemio\mesh_utilities
copying build\lib\bemio\mesh_utilities\mesh.py -> build\bdist.win-amd64\egg\bemio\mesh_utilities
copying build\lib\bemio\mesh_utilities\__init__.py -> build\bdist.win-amd64\egg\bemio\mesh_utilities
creating build\bdist.win-amd64\egg\bemio\runners
copying build\lib\bemio\runners\nemoh.py -> build\bdist.win-amd64\egg\bemio\runners
copying build\lib\bemio\runners\__init__.py -> build\bdist.win-amd64\egg\bemio\runners
creating build\bdist.win-amd64\egg\bemio\utilities
copying build\lib\bemio\utilities\__init__.py -> build\bdist.win-amd64\egg\bemio\utilities
copying build\lib\bemio\__init__.py -> build\bdist.win-amd64\egg\bemio
copying build\lib\bemio\__version__.py -> build\bdist.win-amd64\egg\bemio
byte-compiling build\bdist.win-amd64\egg\bemio\data_structures\bem.py to bem.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\data_structures\wave_excitation.py to wave_excitation.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\data_structures\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\io\aqwa.py to aqwa.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\io\nemoh.py to nemoh.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\io\output.py to output.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\io\wamit.py to wamit.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\io\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\mesh_utilities\mesh.py to mesh.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\mesh_utilities\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\runners\nemoh.py to nemoh.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\runners\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\utilities\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\bemio\__version__.py to __version__.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying bemio.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying bemio.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying bemio.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying bemio.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying bemio.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\bemio-1.1-py2.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing bemio-1.1-py2.7.egg
Removing c:\users\user\appdata\roaming\python\python27\site-packages\bemio-1.1-py2.7.egg
Copying bemio-1.1-py2.7.egg to c:\users\user\appdata\roaming\python\python27\site-packages
bemio 1.1 is already the active version in easy-install.pth

Installed c:\users\user\appdata\roaming\python\python27\site-packages\bemio-1.1-py2.7.egg
Processing dependencies for bemio==1.1
Searching for astropy==1.0.3
Best match: astropy 1.0.3
Adding astropy 1.0.3 to easy-install.pth file
Installing fitsheader-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing fitsheader.exe script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing fits2bitmap-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing fits2bitmap.exe script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing fitsdiff-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing fitsdiff.exe script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing fitscheck-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing fitscheck.exe script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing volint-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing volint.exe script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing wcslint-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing wcslint.exe script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing samp_hub-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing samp_hub.exe script to C:\Users\User\AppData\Roaming\Python\Scripts

Using c:\users\user\anaconda\lib\site-packages
Searching for progressbar2==2.7.3
Best match: progressbar2 2.7.3
Processing progressbar2-2.7.3-py2.7.egg
progressbar2 2.7.3 is already the active version in easy-install.pth

Using c:\users\user\appdata\roaming\python\python27\site-packages\progressbar2-2.7.3-py2.7.egg
Searching for h5py==2.5.0
Best match: h5py 2.5.0
Adding h5py 2.5.0 to easy-install.pth file

Using c:\users\user\anaconda\lib\site-packages
Searching for scipy==0.15.1
Best match: scipy 0.15.1
Adding scipy 0.15.1 to easy-install.pth file

Using c:\users\user\anaconda\lib\site-packages
Searching for numpy==1.9.2
Best match: numpy 1.9.2
Adding numpy 1.9.2 to easy-install.pth file

Using c:\users\user\anaconda\lib\site-packages
Searching for six==1.9.0
Best match: six 1.9.0
Adding six 1.9.0 to easy-install.pth file

Using c:\users\user\anaconda\lib\site-packages
Searching for Cython==0.22.1
Best match: Cython 0.22.1
Adding Cython 0.22.1 to easy-install.pth file
Installing cython-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing cython.exe script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing cygdb-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing cygdb.exe script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing cythonize-script.py script to C:\Users\User\AppData\Roaming\Python\Scripts
Installing cythonize.exe script to C:\Users\User\AppData\Roaming\Python\Scripts

Using c:\users\user\anaconda\lib\site-packages
Finished processing dependencies for bemio==1.1
C:\Users\User\Documents\GitHub\bemio_test [master]> cd .\tutorials\nemoh
C:\Users\User\Documents\GitHub\bemio_test\tutorials\nemoh [master]> ipython
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 3.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: ls
 Volume in drive C has no label.
 Volume Serial Number is 8015-172C

 Directory of C:\Users\User\Documents\GitHub\bemio_test\tutorials\nemoh

08/12/2015  06:08 AM    <DIR>          .
08/12/2015  06:08 AM    <DIR>          ..
08/12/2015  06:08 AM    <DIR>          data
08/12/2015  06:08 AM               620 run.py
               1 File(s)            620 bytes
               3 Dir(s)  454,110,969,856 bytes free

In [2]: run run.py
Calculating the radiation damping impulse response function for Cube.dat:100%||
Calculating the excitation force impulse response function for Cube.dat:100%|#|
Calculating the radiation damping impulse response function for Rotated_cube.dat:100%||
Calculating the excitation force impulse response function for Rotated_cube.dat:100%||
Writing HDF5 data to C:\Users\User\Documents\GitHub\bemio_test\tutorials\nemoh\data\two_body\Nemoh.h5
        Radiation state space coefficients for Cube.dat were not written.
        Radiation state space coefficients for Rotated_cube.dat were not written.
```

**Comment by cmichelen** [comment]
Hi Matt,
Were you able to solve this? Another user is having the same issue... @MalteTwo
