### ISSUE TITLE
Read Nemoh output error

### ISSUE THREAD

**Issue by javierfq** [WEC-Sim/bemio#30]
I have calculated a output nemoh and cannot import from bemio, however i can run the tutorial one_body

The error is the next:

Traceback (most recent call last):
  File "C:\Users\javie_000\Desktop\Software WECs\BEMIO\bemio-master\bemio-master\tutorials\nemoh\Wavestar.py", line 12, in <module>
    nemoh_data_one_body = read(sim_dir='./wavestar_bemio', cal_file='Nemoh.cal', results_dir='Results', mesh_dir='Mesh')
  File "build\bdist.win32\egg\bemio\io\nemoh.py", line 474, in read
    nemoh_data = NemohOutput(sim_dir, cal_file, results_dir, mesh_dir, scale)
  File "build\bdist.win32\egg\bemio\io\nemoh.py", line 92, in __init__
    self._read_cal()
  File "build\bdist.win32\egg\bemio\io\nemoh.py", line 171, in _read_cal
    self.cal.wave_dir_n = np.float(temp.split()[0])
ValueError: could not convert string to float: ---

**Comment by javierfq** [comment]
I found the error

Nemoh.cal have a final line with "---", this must be eliminated for running.

**Comment by cmichelen** [comment]
Another user had this issue with the "---". @lawsonro3 we should try to fix this.

**Comment by lawsonro3** [comment]
Hi All,

I just pushed an update that should fix this bug. Thanks for reporting it and sorry for the slow response.

@cmichelen -  could you check to make sure this is working for you.

Thanks!
